(function(){
'use strict';
const d=typeof CALENDAR_DATA==='undefined'?{currentDay:1,days:[]}:CALENDAR_DATA;const max=100;const current=Math.max(1,Math.min(max,Number(d.currentDay)||1));const $=id=>document.getElementById(id);const storeKey='isekai-calendar-view';let selected=current,refresh=true,lastInput=0;
try{const saved=JSON.parse(sessionStorage.getItem(storeKey)||'null');if(saved){selected=Math.max(1,Math.min(max,Number(saved.day)||current));refresh=saved.refresh!==false}}catch{}
function node(tag,text,cls){const el=document.createElement(tag);if(text!=null)el.textContent=String(text);if(cls)el.className=cls;return el}
function record(day){return(d.days||[]).find(x=>Number(x.day)===day)}
function save(){try{sessionStorage.setItem(storeKey,JSON.stringify({day:selected,refresh,scroll:$('dayContent').scrollTop,gridScroll:$('dayGrid').parentElement.scrollTop}))}catch{}}
function display(day,focus=false){selected=Math.max(1,Math.min(max,day));const entry=record(selected),future=selected>current;for(const cell of $('dayGrid').children){cell.setAttribute('aria-pressed',String(Number(cell.dataset.day)===selected));cell.tabIndex=Number(cell.dataset.day)===selected?0:-1;} $('dayTitle').textContent='DAY '+selected+(selected===current?(d.completed?' · 完結':' · 今日'):future?(d.completed?' · 期限解除':' · これから'):' · 旅の記録');$('previousDay').disabled=selected===1;$('nextDay').disabled=selected===max;
const weather=$('weather');weather.replaceChildren();weather.className='weather-card';weather.append(node('strong',future?'天候：未確定':'天候：'+(entry?.weather?.label||'未記録')));if(!future&&entry?.weather){weather.append(node('p','風：'+(entry.weather.wind||'未記録')));if(entry.weather.note)weather.append(node('p',entry.weather.note));}
const notes=$('dayNotes');notes.replaceChildren();notes.append(node('p',future?(d.completed?'DAY98に本編完結。以降の赤月災害・世界消滅は発生しません。':'この日の出来事は、まだ起きていません。'):entry?.summary||'この日の記録はまだありません。','empty-note'));if(selected%10===0&&!(d.completed&&future)){let moon;if(future)moon='◐ 赤月の予定日。序盤は控えめな警告、日数が進むほど災害の危険が強まります。襲撃や死者は未確定です。';else if(entry?.redMoonObserved)moon='◐ 赤月の観測記録あり。';else moon='◐ 赤月の予定日に該当しますが、この日の赤月は未観測・未記録です。';notes.append(node('p',moon,'moon-note'));}if(selected===100&&!d.completed)notes.append(node('p','DAY100終了が期限。帰還条件を達成していれば成功を優先し、未達なら世界消滅の予定です。画面操作では判定しません。','moon-note'));
for(const warning of d.forewarnings||[]){if(warning.day===selected&&!(d.completed&&future)){notes.append(node('h3',warning.title),node('p',warning.text,'moon-note'));}}
const events=$('dayEvents');events.replaceChildren();if(!future){for(const event of entry?.events||[]){const card=node('article',null,'day-event');card.append(node('h3',(event.scene?'TURN '+event.scene+' · ':'')+(event.title||'絵日記')));if(event.image&&/^assets\//.test(event.image)&&!event.image.includes('..')){const img=node('img');img.src=event.image;img.alt=event.title||'この日の挿絵';img.loading='lazy';img.onerror=()=>{img.hidden=true;card.append(node('p','挿絵ファイルを確認できません。','empty-note'))};card.append(img);const link=node('a','挿絵を原寸で開く');link.href=event.image;link.target='_blank';link.rel='noopener';card.append(link)}if(event.excerpt)card.append(node('p',event.excerpt));const sceneId=/^1-\d+$/.test(event.scene||'')?event.scene:null;if(sceneId){const read=node('a','この話を本文で読む →');read.href='reader.html#scene-'+sceneId;read.style.cssText='display:block;margin:14px 0;font-weight:bold';card.append(read)}card.append(node('p','挿絵は記録された場面の参考です。複数日にまたがる場面は、その注記・本文を優先します。','empty-note'));events.append(card)}if(!entry?.events?.length)events.append(node('p','この日の挿絵記録はありません。','empty-note'));}
$('dayContent').scrollTop=0;if(focus)$('dayGrid').children[selected-1].focus();}
for(let day=1;day<=max;day++){const btn=node('button',null,'day-cell '+(day<current?'past':day===current?'current':'future')+(day%10===0&&!(d.completed&&day>current)?' redmoon':''));btn.type='button';btn.dataset.day=String(day);btn.setAttribute('aria-label','DAY '+day+(day%10===0&&!(d.completed&&day>current)?'、赤月の記録日':'')+(day===current?'、今日':''));btn.append(node('span',day),node('small',day%10===0&&!(d.completed&&day>current)?'◐':record(day)?.events?.length?'絵日記':d.completed&&day>current?'期限解除':''));btn.onclick=()=>display(day);btn.onkeydown=e=>{const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-10,ArrowDown:10};if(e.key in delta){e.preventDefault();display(selected+delta[e.key],true)}else if(e.key==='Home'||e.key==='End'){e.preventDefault();display(e.key==='Home'?1:100,true)}};$('dayGrid').append(btn)}
$('previousDay').onclick=()=>display(selected-1);$('nextDay').onclick=()=>display(selected+1);$('today').onclick=()=>display(current);function refreshLabel(){$('refreshToggle').textContent=refresh?'30秒確認：ON':'自動更新：停止';$('refreshToggle').setAttribute('aria-pressed',String(refresh))}$('refreshToggle').onclick=()=>{refresh=!refresh;refreshLabel();save()};refreshLabel();$('calendarStatus').textContent=d.completed?'DAY98・本編完結 ｜ 33人全員帰還 ｜ 赤月災害・世界消滅の期限は終了':'現在 DAY'+current+(d.currentRedMoon?.status?.startsWith('進行中')?' 赤月・対処前':'')+' ｜ 期限 DAY100終了（成功判定を優先） ｜ 次の赤月 DAY'+(d.nextRedMoonDay??'未確定')+'夜 ｜ 実時間やクリックで作中の日付は進みません。';display(selected);
try{const saved=JSON.parse(sessionStorage.getItem(storeKey)||'null');if(saved)requestAnimationFrame(()=>{$('dayContent').scrollTop=saved.scroll||0;$('dayGrid').parentElement.scrollTop=saved.gridScroll||0})}catch{}
for(const name of ['pointerdown','keydown','wheel','touchstart'])document.addEventListener(name,()=>{lastInput=Date.now()},{passive:true});window.addEventListener('pagehide',save);window.IsekaiLiveRefresh?.start({page:'calendar',enabled:()=>refresh,images:()=>[...document.querySelectorAll('#dayEvents img')].map(i=>i.src),beforeReload:save});
})();
