(function(){'use strict';
const data=window.CREDITS_DATA,slides=data.slides,$=id=>document.getElementById(id),reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let elapsed=0,playing=false,speed=1,index=-1,last=null,started=false,activeArt=0,artRequest=0,teaserBeat=-1;
const starts=[];let total=0;slides.forEach(s=>{starts.push(total);total+=s.duration});
function node(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e}
function format(t){t=Math.floor(t);return Math.floor(t/60)+':'+String(t%60).padStart(2,'0')}
function safePath(p){return typeof p==='string'&&!p.includes('..')&&!/^[a-z]+:/i.test(p)}
function setArt(path){if(!safePath(path))return;const req=++artRequest,target=1-activeArt,img=$(target?'artB':'artA'),old=$(target?'artA':'artB');let shown=false;img.onload=()=>{if(req!==artRequest||shown)return;shown=true;img.classList.add('active');old.classList.remove('active');activeArt=target};img.onerror=()=>{if(req===artRequest)$('status').textContent='挿絵を読み込めません。本文は引き続き読めます。'};img.src=path;if(img.complete&&img.naturalWidth)img.onload()}
function castNodes(target){target.replaceChildren();target.append(node('h2','この旅を歩いた、三十三人。'));const s=slides.find(x=>x.kind==='cast');for(const g of s.groups){const section=node('section',null,'cast-group');section.append(node('h3',g.title),node('p',g.subtitle,'subtitle'));for(const m of g.members){const row=node('div',null,'cast-person');row.append(node('span',m.name,'cast-name'),node('span',m.role,'cast-role'));section.append(row)}target.append(section)}target.append(node('p','全員、生存帰還。','eyebrow'))}
function render(i){index=i;const s=slides[i],stage=$('scene');$('screen').dataset.kind=s.kind;$('chapters').value=String(i);stage.replaceChildren();$('roll').hidden=s.kind!=='cast';stage.hidden=s.kind==='cast';teaserBeat=-1;if(s.image)setArt(s.image);
 if(s.kind==='cast'){castNodes($('rollInner'));$('rollInner').className='roll-inner';$('roll').scrollTop=0}
 else{stage.append(node('span',s.dayLabel||s.eyebrow||'','eyebrow'));if(s.kind==='teaser')stage.append(node('div',null,'dice-mark'));stage.append(node('h2',s.title));for(const line of s.lines||[])stage.append(node('p',line));if(s.kind==='teaser'){const e=node('p','','teaser-text');e.id='teaserText';stage.append(e)}if(s.note)stage.append(node('p',s.note,'small'));if(s.source&&safePath(s.source)){const a=node('a','この場面の記録を読む ↗','source');a.href=s.source;a.target='_blank';a.rel='noopener';a.addEventListener('click',()=>pause());stage.append(a)}if(s.kind==='end'){const b=node('button','もう一度、はじめから','primary');b.onclick=()=>{seek(0);play()};stage.append(b);const a=node('a','100日の旅日誌へ','source');a.href='calendar.html';stage.append(a)}}
 $('status').textContent=s.label;$('previous').disabled=i===0;$('next').disabled=i===slides.length-1;
 const next=slides.slice(i+1).find(x=>x.image);if(next){const pre=new Image();pre.src=next.image}
}
function update(){let i=slides.length-1;for(let k=0;k<slides.length;k++){if(elapsed<starts[k]+slides[k].duration){i=k;break}}if(i!==index)render(i);const s=slides[i],local=Math.max(0,elapsed-starts[i]);if(s.kind==='cast'&&!reduced){const box=$('roll'),inner=$('rollInner');const f=Math.min(1,local/s.duration);inner.style.transform='translateY('+(box.clientHeight-(box.clientHeight+inner.scrollHeight)*f)+'px)'}if(s.kind==='teaser'){let b=0;s.beats.forEach((v,k)=>{if(local>=v.at)b=k});if(b!==teaserBeat){teaserBeat=b;$('teaserText').textContent=s.beats[b].text}}$('seek').value=String(elapsed);$('clock').textContent=format(elapsed)+' / '+format(total);if(elapsed>=total&&playing)pause()}
function label(){$('play').textContent=playing?'一時停止':elapsed>=total?'もう一度':'再生';$('play').setAttribute('aria-pressed',String(playing))}
function begin(){if(started)return;started=true;$('welcome').hidden=true;$('screen').focus()}
function play(){begin();if(elapsed>=total)elapsed=0;playing=true;last=null;label();update()}
function pause(){playing=false;last=null;label()}
function seek(t){begin();elapsed=Math.max(0,Math.min(total,Number(t)||0));last=null;update()}
function step(d){pause();seek(starts[Math.max(0,Math.min(slides.length-1,index+d))])}
function tick(now){if(playing&&!document.hidden){if(last!==null)elapsed=Math.min(total,elapsed+Math.max(0,Math.min((now-last)/1000,.25))*speed);last=now;update()}else last=null;requestAnimationFrame(tick)}
function reading(){pause();begin();const holder=$('readingContent');if(!holder.children.length){for(const s of slides){const a=node('article');a.append(node('small',s.dayLabel||s.eyebrow||s.label),node('h2',s.title));if(s.image){const im=node('img');im.src=s.image;im.alt=s.title;im.loading='lazy';a.append(im)}for(const line of s.lines||[])a.append(node('p',line));for(const b of s.beats||[])a.append(node('p',b.text));if(s.groups)for(const g of s.groups){a.append(node('h3',g.title));const list=node('ul');for(const m of g.members)list.append(node('li',m.name+' — '+m.role));a.append(list)}if(s.note)a.append(node('small',s.note));if(s.dateNote)a.append(node('small',s.dateNote));if(s.source){const link=node('a','本編の記録へ');link.href=s.source;a.append(link)}holder.append(a)}}$('reading').hidden=false;$('reading').focus()}
$('seek').max=String(total);$('durationHint').textContent='約'+Math.ceil(total/60)+'分 ／ 音なし ／ 停止・速度変更できます'+(reduced?'（動きを抑える設定を反映）':'');slides.forEach((s,i)=>{const o=node('option',s.label);o.value=String(i);$('chapters').append(o)});
$('start').onclick=play;$('play').onclick=()=>playing?pause():play();$('previous').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('seek').oninput=e=>seek(e.target.value);$('speed').onchange=e=>{speed=Number(e.target.value);last=null};$('chapters').onchange=e=>{pause();seek(starts[Number(e.target.value)])};$('readAll').onclick=reading;$('readToggle').onclick=reading;$('closeReading').onclick=()=>{$('reading').hidden=true;$('readToggle').focus()};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('status').textContent='この表示環境では全画面にできません。通常表示で再生できます。'}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA|BUTTON|A/.test(e.target.tagName)||!$('reading').hidden)return;if(e.code==='Space'){e.preventDefault();playing?pause():play()}else if(e.key==='ArrowRight'){e.preventDefault();step(1)}else if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}});window.addEventListener('resize',update);
update();requestAnimationFrame(tick);
})();
