(function(){
'use strict';
const pane=document.getElementById('readingPane');
const tabs=[...document.querySelectorAll('[data-tab]')];
const areas={original:document.getElementById('original'),local:document.getElementById('local'),forecast:document.getElementById('forecast'),consequences:document.getElementById('consequences')};
const key='isekai-guide-reader-v1';let active='original',positions={},lastInteraction=0;
function read(){try{return JSON.parse(sessionStorage.getItem(key)||'{}')}catch{return {}}}
function save(){positions[active]=pane.scrollTop;try{sessionStorage.setItem(key,JSON.stringify({active,positions}))}catch{}}
const previous=read();if(areas[previous.active])active=previous.active;positions=previous.positions&&typeof previous.positions==='object'?previous.positions:{};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n}
function display(v){if(v==null)return '未確認';if(typeof v==='boolean')return v?'あり':'なし';if(Array.isArray(v))return v.map(display).join('／');if(typeof v==='object')return Object.entries(v).map(([k,x])=>k+'：'+display(x)).join('\n');return String(v)}
function article(area,title,tag){const n=el('article');if(tag)n.append(el('span',tag,'tag'));n.append(el('h2',title));area.append(n);return n}
function paras(parent,items,empty='まだ記録されていません。'){if(items==null||Array.isArray(items)&&!items.length){parent.append(el('p',empty,'empty'));return}for(const item of Array.isArray(items)?items:[items])parent.append(el('p',display(item)))}
function rows(parent,items){const dl=el('dl');for(const [label,v]of items){dl.append(el('dt',label),el('dd',display(v)))}parent.append(dl)}
function links(parent,sources){for(const s of sources||[]){if(!s||!/^https?:\/\//i.test(s.url||''))continue;const line=el('p',undefined,'source'),a=el('a',s.title||'原作の参照元');a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';line.append(a);parent.append(line)}}
function show(id,focus=false){if(!areas[id])return;positions[active]=pane.scrollTop;active=id;for(const t of tabs){const on=t.dataset.tab===id;t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1;if(on&&focus)t.focus()}for(const [k,a]of Object.entries(areas))a.hidden=k!==id;pane.scrollTop=Number(positions[id])||0;if(id==='consequences')window.IsekaiNewContent?.mark('guide-consequences');save()}
for(const t of tabs)t.onclick=()=>show(t.dataset.tab);document.querySelector('.tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=tabs.findIndex(t=>t.dataset.tab===active);i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;show(tabs[i].dataset.tab,true)});
if(typeof GUIDE_DATA==='undefined'){paras(areas.original,'記録データを読み込めませんでした。guide-data.jsをこのHTMLと同じフォルダに置いてください。');document.getElementById('sceneLabel').textContent='データ未読込';}else{
 const d=GUIDE_DATA,ability=d.guideAbility||{},teacher=d.teacher||{},details=teacher.uniqueSkillDetails||{},arrows=d.arrowSupply||{},inventory=d.inventoryAudit||{};
 document.getElementById('sceneLabel').textContent='TURN '+display(d.sceneId)+' · '+display(d.asOf);
 document.getElementById('teacherLabel').textContent='先生 · Lv'+display(teacher.level)+' · '+display(teacher.job);
 document.getElementById('walletLabel').textContent='共同ルーン '+display(d.runeBalance);
 document.getElementById('arrowLabel').textContent='通常矢 '+display(arrows.ordinaryArrowCount??inventory.arrows)+'本';
 const progress=d.progress||{},challenge=d.challenge||{};const pct=progress.percent==null?NaN:Number(progress.percent),bar=document.getElementById('returnProgress');document.getElementById('progressLabel').textContent=progress.label||'帰還進捗';if(Number.isFinite(pct)){const n=Math.max(0,Math.min(100,pct));bar.value=n;document.getElementById('progressValue').textContent=n+'%'}else{bar.removeAttribute('value');document.getElementById('progressValue').textContent='未確認'}document.getElementById('progressBasis').textContent=progress.basis||'原作の達成率ではなく、この卓の目安です。';document.getElementById('deadlineValue').textContent=challenge.dayLimit==null||challenge.currentDay==null?'期限・現在日：未確認':'期限 DAY'+display(challenge.dayLimit)+' ／ 現在 DAY'+display(challenge.currentDay);document.getElementById('daysRemaining').textContent=challenge.daysUntilFinalDay==null?'期限日まで：未確認':'期限日まで '+display(challenge.daysUntilFinalDay)+' 日';const moon=challenge.redMoon||{};document.getElementById('redMoon').textContent=(moon.currentEventStatus?.startsWith('進行中')?'現在 DAY'+display(moon.currentEventDay)+' 赤月・対処前 ／ ':'')+(moon.nextDay==null?'次の赤い満月：未確認':'次の赤い満月 DAY'+display(moon.nextDay)+' 夜');document.getElementById('deadlinePolicy').textContent=[challenge.deadlineText,challenge.countPolicy,challenge.redMoon?.effect,'現実の時間や画面の自動更新では日数は進みません。'].filter(Boolean).map(display).join(' ');

 const ab=article(areas.original,ability.name||teacher.uniqueSkill||'攻略サイト先読み','能力の読み方');paras(ab,details.effect||ability.effect||'原作の攻略情報を参照し、現地で検証するための能力。');paras(ab,details.limits||ability.limits||'この世界との一致、現在の敵配置、未来の判定結果や人物の内心は分かりません。');
 const facts=article(areas.original,'質問済みの原作情報','開くと既知の攻略情報を表示');const spoiler=el('details'),summary=el('summary','原作の攻略情報を開く（先の展開を含みます）');spoiler.append(summary);for(const f of ability.originalGameFacts||[]){paras(spoiler,f.text||f);links(spoiler,[f])}if(!ability.originalGameFacts?.length)paras(spoiler,null);facts.append(spoiler);
 const origin=article(areas.original,'矢の補充・製作','原作情報');origin.append(el('p','以下は原作内の価格とレシピです。本卓の見積額・所持材料・購入結果とは別です。','caution'));
 const o=arrows.original||{};rows(origin,[['通常矢の単価',o.arrowUnitPrice==null?null:o.arrowUnitPrice+'ルーン'],['ツール鞄',o.kitPrice==null?null:o.kitPrice+'ルーン'],['必要な製法書',o.cookbookPrice==null?null:o.cookbookPrice+'ルーン'],['骨の矢',o.boneArrowRecipe],['羽付きの骨の矢',o.fletchedRecipe]]);links(origin,arrows.sources);
 const knowledge=d.knowledgeState;if(knowledge){const sharing=article(areas.local,'誰が知っている情報か','プレイヤー向けの記録');sharing.append(el('p',knowledge.disclosureStatus||'共有状況未記録','caution'));sharing.append(el('h3','先生だけの情報'));paras(sharing,knowledge.teacherOnly);sharing.append(el('h3','クラスに共有済み'));paras(sharing,knowledge.classShared);sharing.append(el('p',knowledge.source||'この手帳やHUDはプレイヤー向けです。表示内容が全NPCへ共有されたことにはなりません。','caution'));}
 const local=article(areas.local,'この世界で確認したこと','現地確認');paras(local,ability.observed);
 const stock=article(areas.local,'現在の矢と製作の準備','現地確認');paras(stock,arrows.status);rows(stock,[['通常矢',arrows.ordinaryArrowCount??inventory.arrows],['今回の購入',arrows.purchasedThisTurn===true?'購入済み':'未購入'],['ツール鞄',arrows.craftingKitOwned==null?'未確認':arrows.craftingKitOwned?'所持':'未所持'],['製法書',arrows.cookbookOwned==null?'未確認':arrows.cookbookOwned?'所持':'未所持'],['細い獣骨',arrows.thinBeastBones],['風切羽',arrows.flightPinion]]);
 const quote=article(areas.local,'現地の見積もり','本卓の会計');quote.append(el('p','見積もりを読むだけでは購入・支払い・製作は実行されません。原作価格を自動でこの財布から引きません。','caution'));if(arrows.localQuotes?.length){const wrap=el('div',undefined,'table-wrap'),table=el('table'),head=el('thead'),tr=el('tr');for(const h of ['品目','単価','数量','見積額','条件'])tr.append(el('th',h));head.append(tr);table.append(head);const body=el('tbody');for(const q of arrows.localQuotes){const row=el('tr');for(const v of [q.item,q.unitPrice,q.quantity,q.cost,q.note])row.append(el('td',display(v)));body.append(row)}table.append(body);wrap.append(table);quote.append(wrap)}else paras(quote,null,'現地の見積もりはまだ確定していません。');
 const victory=article(areas.local,'女神との帰還条件','本卓で確認した約束');const v=d.victoryCondition||{};rows(victory,Object.entries({objective:'クリア目標',eligible:'帰還する人',teacher:'先生の扱い',scope:'範囲',notEnough:'達成に足りないこと',source:'確認先',communicationLimits:'伝達・共有の限界'}).filter(([k])=>v[k]!=null).map(([k,l])=>[l,v[k]]));
 const routes=d.routes||{};if(routes.goal||routes.defaultPlan){const goal=article(areas.forecast,'城主戦前の方針記録','DAY41当時の計画');paras(goal,routes.goal);paras(goal,routes.defaultPlan);goal.append(el('p','強化して先へ進むか、補給を整えるか、出会った人の話を聞くか。選択・受諾・出発はチャットで。','caution'));}for(const route of routes.options||[]){const card=article(areas.forecast,route.title||'進路の候補','DAY41当時の選択肢');rows(card,[['目的',route.goal],['次にすること',route.next],['必要な準備',route.requires],['危険・未確認',route.risk],['当時の扱い',route.status]])}
 const expedition=d.currentSceneSummary?{current:d.currentSceneSummary.location,route:[d.currentSceneSummary.summary],travel:d.currentSceneSummary.at,teacherInjury:d.teacher?.condition,unusedGraceCount:d.checkpoint?.reserveCandidates?.length,notYet:[d.nextDecision?.action||'次の判断待ち']}:d.castleExploration51||d.castleExploration50||d.castleExploration49;if(expedition){const result=article(areas.forecast,'現在の探索','現地確認');rows(result,[['現在地',expedition.current],['行程',expedition.route],['移動',expedition.travel],['先生の状態',expedition.teacherInjury],['矢',arrows.ordinaryArrowCount??inventory.arrows],['共同ルーン',d.runeBalance],['未解放の祝福',expedition.unusedGraceCount],['次に確かめること',expedition.notYet]]);}
 const budget=d.campaignBudget;if(budget&&challenge.status!=='completed'){const remaining=Number.isFinite(budget.remainingUsableDays)?budget.remainingUsableDays:Number.isFinite(challenge.dayLimit)&&Number.isFinite(challenge.currentDay)?Math.max(0,(budget.day100Playable===false?challenge.dayLimit-1:challenge.dayLimit)-challenge.currentDay+1):budget.remainingDaysInclusive;const b=article(areas.forecast,(Number.isFinite(budget.remainingUsableDays)?'今後使える':'今日を含む残り')+display(remaining)+'日の配分','保証ではない計画');paras(b,'DAY'+display(challenge.currentDay)+'〜'+display(budget.day100Playable===false?challenge.dayLimit-1:challenge.dayLimit)+'。進捗'+display(progress.percent)+'%は卓の目安で、残日数へ線形換算しません。');for(const block of budget.blocks||[]){const end=Number(String(block.days).split(/[–−-]/).pop());if(Number.isFinite(end)&&end<challenge.currentDay)continue;paras(b,'DAY'+block.days+'：'+block.goal)}paras(b,budget.remainingDaysNote);paras(b,budget.review);paras(b,budget.conclusion);paras(b,budget.limits);paras(b,budget.level80Note);}
 const recovery=article(areas.local,'回復の確認','本卓の導入');paras(recovery,d.healingPreparation);
 const support=d.availableSupportReview;if(support){const a=article(areas.local,'支援候補の点検記録',support.asOf||'過去の記録');for(const x of support.recommendations||[])rows(a,[[x.name,x.tool+'：'+x.use+' '+x.limit]]);paras(a,support.excluded);paras(a,support.allocation);} const future=d.futureEquipmentDiscussion;if(future){const a=article(areas.forecast,'円卓での装備配備記録','DAY39–40当時／現在装備は名鑑へ');paras(a,future);}
 const hr=d.halberdReview;if(hr){const h=article(areas.local,'黄金のハルバード','原作参考と現物評価');rows(h,[['戦技',hr.skill],['効果',hr.effect],['必要能力',hr.requirements],['現状',hr.status],['未設定',hr.limits]]);links(h,hr.sources);}
 const mount=d.mountCare;if(mount){const a=article(areas.local,'軍馬の世話','段階的な接触・未騎乗');rows(a,[['状態',mount.status],['担当',Object.values(mount.caretakers||{}).join('／')],['最後の目撃',(mount.lastSeen?.at||'')+' '+(mount.lastSeen?.place||'')],['次の段階',mount.next]]);a.append(el('p','段階は乗れる確率ではありません。未捕獲・未収容で、現在位置は最後の目撃地点です。','caution'));}
 const recon=d.teacherReconPlan, travel=d.personalFastTravelRule;if(recon){const a=article(areas.forecast,'次の行動と帰還','計画・自動実行なし');rows(a,[['状況',recon.status],['目的',recon.intent],['交戦',recon.attack||'出撃前に方針を確認'],['乗り物',recon.mount],['帰還',recon.return],['24時間未帰還',recon.overdue?.trigger],['救援',recon.overdue?.action],['復活の条件',recon.overdue?.effect]]);paras(a,recon.overdue?.limits);}if(travel){const a=article(areas.forecast,'本人の祝福登録と転送','本人の到達と解放が必要');rows(a,[['移動先',travel.allowed],['未解放の祝福',travel.unopened],['戦闘中',travel.combat],['復活との違い',travel.revivalException]]);if(travel.roundtableException){a.append(el('h3','円卓だけの同行例外'));paras(a,travel.roundtableException);}}
 const morgott=article(areas.original,'攻略記録：忌み王モーゴット（撃破済み）','原作情報とDAY74の攻略記録');morgott.id='morgott-plan';paras(morgott,['光の武器を持ち替える連撃と、溜めてから放つ槍投げに注意。早い回避を連打せず、投擲を見て避ける。','降る剣は落下範囲の隙間へ。床の異変が広がる場面では密集せず退路を分ける。','メリナの召喚印は原作の助力候補。DAY74に現地の印で召喚し共闘済み。以下は原作情報の記録。']);links(morgott,[{title:'原作：王都攻略とモーゴット',url:'https://www.powerpyx.com/elden-ring-leyndell-royal-capital-walkthrough/'}]);const routePlan=article(areas.forecast,'通常ルートと日程','計画・到達や勝利の確定ではない');paras(routePlan,['モーゴット → 火の巨人 → 神肌のふたり／マリケス → ギデオン／実体ゴッドフレイ → ラダゴン／エルデの獣。','DAY96達成を目標に97–99を予備とする。DAY100を使える行動日に含めない。未踏の地点・敵は先読み情報で、現地確認を意味しない。']);links(routePlan,[{title:'原作：通常ルートのボス順',url:'https://www.gamesradar.com/elden-ring-main-bosses-required/'}]);
 const lore=d.loreReview;if(lore){const a=article(areas.local,'考察を読む','攻略サイト先読みの読書モード');a.id='lore-review';paras(a,lore.summary||lore.scope||'原作事実・解釈・現地の確認を分けて記録します。新しい能力や未来予知の取得ではありません。');for(const [key,label] of [['originalFacts','原作で確認できること'],['hypotheses','考察・仮説'],['localObservations','この世界で確認したこと']]){a.append(el('h3',label));const entries=lore[key]||[];if(!entries.length)paras(a,null,'まだ記録はありません。');for(const entry of entries){if(typeof entry==='string'){paras(a,entry);continue}if(entry.title)a.append(el('h4',entry.title));paras(a,entry.text||entry.summary||entry.claim);if(entry.caveat)paras(a,entry.caveat);links(a,entry.sources||(entry.url?[{title:entry.sourceTitle||entry.title||'出典',url:entry.url}]:[]));}}paras(a,lore.limits||'考察は確定設定ではなく、この世界での一致も未確認です。');}
 const allies=d.npcAllies50;if(allies){const a=article(areas.local,'城で得た協力者','DAY41の会話記録');a.id='castle-allies';for(const npc of allies){a.append(el('h3',npc.name));rows(a,[['目的',npc.motivation],['協力',npc.support],['当時の扱い',npc.note]]);}}
 const works=d.campWorks49;if(works){const a=article(areas.local,'教会の仮補修の記録','DAY41着手／DAY45追記');rows(a,[['指揮',works.leader],['着想',works.design+' ／ '+works.inspection]]);paras(a,works.done);paras(a,works.latest);a.append(el('h3','当時の未完事項'));paras(a,works.notDone);paras(a,works.benefit);}
 const unknown=article(areas.forecast,'まだ確かめていないこと','未確認');paras(unknown,ability.unverified);
 const forecasts=d.forecast||[];if(!forecasts.length){const f=article(areas.forecast,'次の判断へ');paras(f,null,'条件付きの見通しはまだ記録されていません。')}for(const f of forecasts){const card=article(areas.forecast,f.title||'条件付きの見通し','予測 · 結果の確定ではありません');rows(card,[['成り立つ条件',f.condition],['期待できること',f.expectation],['不確かなこと',f.uncertainty],['現地で確かめること',f.check]])}
}

const consequenceData=typeof GUIDE_CONSEQUENCES==='undefined'?[]:GUIDE_CONSEQUENCES.items||[];
const consequenceIndex=el('div',undefined,'consequence-index'),consequenceDetail=el('article',undefined,'consequence-detail');areas.consequences.append(el('h2','選ぶ前に、思い出す。'),el('p','原作の条件と、この世界での実績を分けて読む手帳。本文は選んだ項目だけ開きます。'),consequenceIndex,consequenceDetail);
function pickConsequence(id){const item=consequenceData.find(x=>x.id===id);if(!item)return;consequenceDetail.replaceChildren(el('h3',item.title),el('p',item.prompt));const fold=el('details'),summary=el('summary',item.spoiler+' — 詳細を開く');fold.append(summary,el('h4','原作で確認されている条件'));paras(fold,item.facts,'原作仕様ではなく、本卓の取り決めです。');links(fold,item.sources);fold.append(el('h4','考察・判断の手掛かり'));paras(fold,item.interpretation);fold.append(el('h4','現地・本卓の確認'));paras(fold,item.id==='personal-travel'&&typeof GUIDE_DATA!=='undefined'&&GUIDE_DATA.personalFastTravelRule?GUIDE_DATA.personalFastTravelRule:item.local);consequenceDetail.append(fold);for(const button of consequenceIndex.children)button.setAttribute('aria-pressed',String(button.dataset.id===id));}
for(const item of consequenceData){const button=el('button',item.title);button.type='button';button.dataset.id=item.id;button.setAttribute('aria-pressed','false');button.onclick=()=>pickConsequence(item.id);consequenceIndex.append(button)}
function openConsequenceHash(){if(!location.hash.startsWith('#consequences'))return;active='consequences';show('consequences');const id=location.hash.split('/')[1]||'academy-plan';pickConsequence(id);const fold=consequenceDetail.querySelector('details');if(fold)fold.open=true;}openConsequenceHash();window.addEventListener('hashchange',openConsequenceHash);

if(location.hash==='#lore-review')active='local';
for(const [k,a]of Object.entries(areas))a.hidden=k!==active;for(const t of tabs){const on=t.dataset.tab===active;t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1}requestAnimationFrame(()=>{pane.scrollTop=Number(positions[active])||0});
for(const event of ['pointerdown','keydown','wheel','touchstart'])document.addEventListener(event,()=>{lastInteraction=Date.now()},{passive:true});pane.addEventListener('scroll',()=>{lastInteraction=Date.now();save()},{passive:true});window.addEventListener('pagehide',save);
function openLore(){if(location.hash!=='#lore-review')return;active='local';for(const [k,a]of Object.entries(areas))a.hidden=k!==active;for(const tab of tabs){const on=tab.dataset.tab===active;tab.setAttribute('aria-selected',String(on));tab.tabIndex=on?0:-1}const target=document.getElementById('lore-review');if(target){target.classList.add('new-content-target');target.scrollIntoView({block:'start'});window.IsekaiNewContent?.mark('guide-lore')}save()}requestAnimationFrame(openLore);window.addEventListener('hashchange',openLore);

if(typeof GUIDE_DATA!=='undefined'){
 const d=GUIDE_DATA,now=d.currentSceneSummary||{},a=article(areas.local,(now.at||d.asOf||'現在')+'・現在の状況','最新の現地記録');a.id='day79-status';areas.local.prepend(a);
 const levels=(d.loadouts||[]).map(c=>c.level).filter(Number.isFinite),students=levels.length?`${levels.length}人／Lv${Math.min(...levels)}–${Math.max(...levels)}`:'名鑑を参照';
 rows(a,[['現在地',now.location||d.destination?.current],['育成',`先生Lv${d.teacher?.level??'未確認'}／生徒${students}`],['移動用祝福',`解放${d.checkpoint?.activated?.length??'未確認'}・予備${d.checkpoint?.reserveCandidates?.length??'未確認'}。個人の到達・登録範囲は地図を参照。`],['赤月',d.challenge?.status==='completed'?'終了':`DAY${d.challenge?.redMoon?.nextDay??'未確認'}夜`],['帰還',d.challenge?.status==='completed'?'33人全員帰還。期限解除。':`${d.campaignBudget?.remainingUsableDays??'未確認'}日。DAY100は攻略の予備日に含めない。`],['物資（帰還前の保存記録）',`共同ルーン${d.runeBalance??'未確認'}／通常矢${d.arrowSupply?.ordinaryArrowCount??'未確認'}本／食料${d.foodInventory?.availablePortions??'未確認'}食／飲用水${d.waterLedger?.closingPotableLitres??'未確認'}L`],['軍馬',d.mountCare?.status||'記録なし']]);
 const arcLink=el('a','DAY90–92をまとめて読む');arcLink.href='story/finale-days90-92.html';a.append(arcLink);paras(a,now.summary);paras(a,d.nextDecision?.action);
 document.getElementById('daysRemaining').textContent='残り行動日 '+(d.campaignBudget?.remainingUsableDays??'未確認')+' 日（DAY100を除く）';
}
function openCurrentStatus(){if(location.hash!=='#day79-status')return;show('local');const a=document.getElementById('day79-status');a?.scrollIntoView({block:'start'});window.IsekaiNewContent?.markHref('guide.html#day79-status')}
requestAnimationFrame(openCurrentStatus);window.addEventListener('hashchange',openCurrentStatus);

window.IsekaiLiveRefresh?.start({page:'guide',beforeReload:save});

if(typeof GUIDE_DATA!=='undefined'&&GUIDE_DATA.smithing105){
 const m=GUIDE_DATA.smithing105,a=article(areas.local,'DAY95・強化と調霊','実施済みの注文と補修');a.id='equipment-day95';
 rows(a,[['支出',`${m.totalSpending}ルーン（当日開始資金の${m.percentageOfOpening}%）`],['DAY95終了時残額','4736ルーン（当時の強化会計）'],['通常鍛石', '鈴玉1〜4奉納済み。素材の販売解放と購入・消費は別に記録。'],['クララ',`+${GUIDE_DATA.roderikaTuning105?.clara??1}。強化後の実戦未検証、召喚回数は増えない。`],['補修',`${m.repairs.length}点・${m.repairCost}ルーン（上記支出に含む）`]]);
 const table=el('table'),head=el('thead'),hr=el('tr');for(const v of ['使用者','装備','強化前→後'])hr.append(el('th',v));head.append(hr);table.append(head);const body=el('tbody');
 for(const o of [...m.normalOrders,...m.somberOrders]){const tr=el('tr');for(const v of [o.owner,o.name,`+${o.from} → +${o.to}`])tr.append(el('td',v));body.append(tr)}table.append(body);a.append(table);areas.local.prepend(a);
 function openEquipment(){if(location.hash!=='#equipment-day95')return;show('local');a.scrollIntoView({block:'start'});window.IsekaiNewContent?.markHref('guide.html#equipment-day95')}requestAnimationFrame(openEquipment);window.addEventListener('hashchange',openEquipment);
}

if(typeof GUIDE_DATA!=='undefined'&&GUIDE_DATA.battle106){const b=GUIDE_DATA.battle106,a=article(areas.local,'DAY96・第一王との再戦','現地結果');a.id='throne-day96';rows(a,[['結果','第一王・ホーラ・ルー撃破。新死亡・新負傷なし。'],['判定',b.checks.filter(c=>c.id!=='base').map(c=>`${c.label}：${c.total}`).join('／')],['祝福',b.grace+'：主力13人が新解放・個人登録。'],['DAY96終了時','全33人エレの教会へ帰還。最終連戦は当時未交戦。'],['クララ',b.clara],['追憶','未使用・共同保管。']]);areas.local.prepend(a);function openBattle(){if(location.hash!=='#throne-day96')return;show('local');a.scrollIntoView({block:'start'})}requestAnimationFrame(openBattle);window.addEventListener('hashchange',openBattle);}

if(typeof GUIDE_DATA!=='undefined'&&GUIDE_DATA.preparation107){const p=GUIDE_DATA.preparation107,e=GUIDE_DATA.endingDiscussion107,a=article(areas.local,'DAY97午前・最終戦前の準備記録','当時の準備内容／現在の結果は最新欄へ');a.id='final-preparation-day97';rows(a,[['会計',`追憶換金後${p.openingIncludingRemembrance} − 準備費${p.totalSpending} = 残${p.balance}ルーン`],['武器',p.orders.map(o=>`${o.owner}：${o.name} +${o.from}→+${o.to}`).join('／')],['防具配分',p.armor.map(o=>o.owner+'：'+o.name).join('／')],['先生の聖杯瓶','回復強化+1、赤4・青0。回数は増えない。'],['大ルーン','ゴドリックの大ルーン装備・弧1使用。先生の全能力+5、基礎Lv80と基礎能力は不変。予備弧1。死亡または解除まで。'],['紬の準備','王たる聖防護＋回復の2枠。炎は今回は外す。既定の共有回数を使用。'],['準備時点','この準備記録の時点では最終戦未開始。残日数と現在結果は最新欄を参照。']]);a.append(el('h3','帰還の約束と、まだ答えのない願い'));paras(a,e.status);paras(a,e.returnContract.objective);paras(a,e.returnContract.eligible);paras(a,e.returnContract.teacher);paras(a,e.returnContract.deadline);paras(a,e.hopes);a.append(el('h4','未確認'));paras(a,e.notConfirmed);paras(a,e.principle);areas.local.prepend(a);function openPreparation(){if(location.hash!=='#final-preparation-day97')return;show('local');a.scrollIntoView({block:'start'})}requestAnimationFrame(openPreparation);window.addEventListener('hashchange',openPreparation);}

if(GUIDE_DATA.finalRescueProtocol97){const p=GUIDE_DATA.finalRescueProtocol97,a=article(areas.local,'伝令が戻らない時の定時救援','DAY97追加命令／未実行');a.id='final-rescue-day97';rows(a,[['担当',p.leader+'（代行 '+p.deputy+'）／C隊6名'],['時刻',p.start+'、毎日'+p.dailyTime+'、DAY100まで'],['発動',p.trigger],['行動',p.action],['候補順',p.queue.join(' → ')],['経路',p.queueRule],['配置',p.preposition],['復活',p.effect],['再出撃の条件',p.restartGate],['終了',p.stop],['先生と指揮',p.teacherOrder]]);a.append(el('h3','この仕掛けの限界'));paras(a,p.limits);areas.local.prepend(a);function rescueHash(){if(location.hash==='#final-rescue-day97'){show('local');a.scrollIntoView({block:'start'})}}requestAnimationFrame(rescueHash);window.addEventListener('hashchange',rescueHash);}

if(typeof GUIDE_DATA!=='undefined'&&GUIDE_DATA.battle108){const b=GUIDE_DATA.battle108,a=article(areas.local,'DAY97夕・最終二連戦の記録','戦闘終了時点／その後は最新欄へ');a.id='final-battle-turn108';rows(a,[['戦闘結果','ラダゴン・エルデの獣撃破。新死亡0、負傷2名は回復済み。'],['帰還時点','全33人エレの教会、休息済み。'],['祝福','壊れかけのマリカ：主力13人が解放・個人登録。'],['救援','C隊は対面報告を受け帰投。翌朝の新規祝福解放は取消。'],['戦闘終了時の判断','この記録時点ではエンディング未操作。以後の女神との会話と選択は最新欄を参照。'],['計画','安全側の行動日はDAY98〜99の2日。期限はDAY100終了。']]);paras(a,GUIDE_DATA.victoryCondition?.eligible);paras(a,GUIDE_DATA.victoryCondition?.teacher);areas.local.prepend(a);function openFinal(){if(location.hash!=='#final-battle-turn108')return;show('local');a.scrollIntoView({block:'start'})}requestAnimationFrame(openFinal);window.addEventListener('hashchange',openFinal);}

if(typeof GUIDE_DATA!=='undefined'&&GUIDE_DATA.goddessGuide109){const g=GUIDE_DATA.goddessGuide109,a=article(areas.local,'DAY97夜・女神との対話と、残すもの','現地の対話／原作のエンディングとは区別');a.id='goddess-turn109';paras(a,g.summary);rows(a,g.rows);if(g.paragraphs.length)paras(a,g.paragraphs);const link=el('a','本編：女神との対話を読む');link.href='story/goddess-turn109.html';a.append(link);areas.local.prepend(a);function openGoddess(){if(location.hash!=='#goddess-turn109')return;show('local');a.scrollIntoView({block:'start'});window.IsekaiNewContent?.markHref('guide.html#goddess-turn109')}requestAnimationFrame(openGoddess);window.addEventListener('hashchange',openGoddess);}

if(GUIDE_DATA.challenge?.status==='completed'){
 document.getElementById('deadlineValue').textContent='DAY98・期限内に結末成立';
 document.getElementById('daysRemaining').textContent='帰還達成・33人全員生存';
 document.getElementById('redMoon').textContent='赤月災害は終了';
 document.getElementById('deadlinePolicy').textContent='DAY100の世界消滅条件は解除。狭間の地は存続します。';
 const g=GUIDE_DATA.endingGuide110,a=article(areas.local,'DAY98・結末と帰還','本編完結／原作の王エンドと本卓の帰還を区別');a.id='ending-turn110';paras(a,g.summary);rows(a,g.rows);paras(a,g.paragraphs);const link=el('a','エンディングを読む');link.href='story/ending-day98.html';a.append(link);areas.local.prepend(a);
 for(const section of Object.values(areas)){for(const h of section.querySelectorAll('h2,h3')){if(h.textContent==='現在の探索')h.textContent='帰還後の状態と冒険の記録';}}
 function openEnding(){if(location.hash!=='#ending-turn110')return;show('local');a.scrollIntoView({block:'start'});window.IsekaiNewContent?.markHref('guide.html#ending-turn110')}requestAnimationFrame(openEnding);window.addEventListener('hashchange',openEnding);
}
})();
