(function(){'use strict';
const entries=[
{"key": "reader-context", "version": "2026-09-25", "label": "通読：挿絵を大きく表示・この日の記録", "href": "reader.html", "selector": "#readerLink"},
{"key": "story-reader", "version": "complete-110", "label": "DAY1から本文を通読・日付選択としおり", "href": "reader.html#day-1", "selector": "#readerLink"},
{"key": "end-credits", "version": "1-110-credits", "label": "DAY1–98・エンドロールと、そのあと", "href": "credits.html", "selector": "#creditsLink"},
{"key": "ending110", "version": "1-110", "label": "DAY98・結末と帰還", "href": "story/ending-day98.html", "selector": "#guideToggle"},{"key": "ending-guide110", "version": "1-110", "label": "DAY98・世界の存続と33人の帰還", "href": "guide.html#ending-turn110", "selector": "#guideToggle"},
{"key": "goddess109", "version": "1-109", "label": "DAY97・女神への相談と、残すもの", "href": "story/goddess-turn109.html", "selector": "#guideToggle"},{"key": "goddess-guide109", "version": "1-109", "label": "DAY97・女神との対話と託す資金", "href": "guide.html#goddess-turn109", "selector": "#guideToggle"},
{"key": "final-battle108", "version": "1-108", "label": "DAY97・最終二連戦", "href": "story/final-battle-turn108.html", "selector": "#guideToggle"},
{"key": "final-rescue97", "version": "1-107-rescue", "label": "DAY97・伝令なしの定時救援", "href": "guide.html#final-rescue-day97", "selector": "#guideToggle"},
{"key": "final-preparation97", "version": "1-107", "label": "DAY97・最終戦の前に", "href": "story/final-preparation-day97.html", "selector": "#guideToggle"},
{"key": "reference-student-01", "version": "1-106", "label": "佐伯 直人・現装備の立ち絵", "href": "board.html#student-01", "selector": "#rosterToggle"},
{"key": "reference-student-19", "version": "1-106", "label": "久我 大地・現装備の立ち絵", "href": "board.html#student-19", "selector": "#rosterToggle"},
{"key": "throne96", "version": "1-106", "label": "DAY96・第一王への再挑戦", "href": "story/throne-day96.html", "selector": "#guideToggle"},
{"key": "equipment95", "version": "1-105", "label": "DAY95・強化14品とクララの調霊", "href": "guide.html#equipment-day95", "selector": "#guideToggle"},
{"key": "smithing95", "version": "1-105", "label": "DAY95・再戦への準備", "href": "story/smithing-day95.html", "selector": "#guideToggle"},
{"key": "smithing94", "version": "1-104", "label": "DAY94・再戦への準備", "href": "story/smithing-day94.html", "selector": "#guideToggle"},
{"key": "story-tsubasa", "version": "1-103", "label": "翼の掌編・六人帰還", "href": "side-stories.html#tsubasa-six-returned", "selector": "#rosterToggle"},
{"key": "throne93", "version": "1-103", "label": "DAY93・第一王の拳と持ち帰った力", "href": "story/throne-day93.html", "selector": "#guideToggle"},
{"key": "finale92", "version": "1-102", "label": "DAY90–92・赤い雨から灰都と神授塔へ", "href": "story/finale-days90-92.html", "selector": "#guideToggle"},
{"key": "finale91", "version": "1-101", "label": "DAY91・黒き剣から灰の王都へ", "href": "story/finale-day91.html", "selector": "#guideToggle"},
{"key": "finale90", "version": "1-100", "label": "DAY90・赤い雨の防衛と新たな準備", "href": "story/finale-day90.html", "selector": "#guideToggle"},
{"key": "farum89", "version": "1-99", "label": "DAY86–89・黒き剣から教会へ", "href": "story/farum-days86-89.html", "selector": "#guideToggle"},
{"key": "farum88", "version": "1-98", "label": "DAY88・門番と黒き剣", "href": "story/farum-day88.html", "selector": "#guideToggle"},
{"key": "farum87", "version": "1-97", "label": "DAY87・雷を迂回し大橋の脇へ", "href": "story/farum-day87.html", "selector": "#guideToggle"},
{"key": "farum86", "version": "1-96", "label": "DAY86・補給と竜の聖堂の屋根へ", "href": "story/farum-day86.html", "selector": "#guideToggle"},
{"key": "giants85", "version": "1-95", "label": "DAY82–85・釜から神肌のふたりまで", "href": "story/giants-days82-85.html", "selector": "#guideToggle"},
{"key": "giants84", "version": "1-94", "label": "DAY84・竜の聖堂まで", "href": "story/giants-day84.html", "selector": "#guideToggle"},
{"key": "giants83", "version": "1-93", "label": "DAY83・釜の別れと崩れゆく獣墓", "href": "story/giants-day83.html", "selector": "#guideToggle"},
{"key": "giants82", "version": "1-92", "label": "DAY82・火の巨人との戦い", "href": "story/giants-day82.html", "selector": "#guideToggle"},
{"key": "redmoon81", "version": "1-91", "label": "DAY81・補給と火の釜の麓へ", "href": "story/redmoon-day81.html", "selector": "#guideToggle"},
{"key": "redmoon80", "version": "1-90", "label": "DAY80赤月から翌朝へ", "href": "story/redmoon-day80.html", "selector": "#guideToggle"},
{"key": "story-riku79", "version": "day79-maintenance-1", "label": "陸の掌編「剣を置く場所」・挿絵付き", "href": "side-stories.html#riku-room-for-a-blade", "selector": "#rosterToggle"},
{"key": "mountaintops75-79", "version": "1-89", "label": "DAY75–79：雪山への五日間・5話", "href": "story/mountaintops-days75-79.html", "selector": "#guideToggle"},
{"key": "guide-current79", "version": "day79-maintenance-1", "label": "攻略手帳 → DAY79帰還後の現在地・残り20行動日", "href": "guide.html#day79-status", "selector": "#guideToggle"},
{"key": "world-mountaintops79", "version": "1-89", "label": "全体地図 → 火の釜の麓・主力13人の登録", "href": "world-map.html#grace-38", "selector": "#routePlanLink"},
{"key": "roster-current79", "version": "day79-maintenance-1", "label": "生徒名鑑 → DAY75–79の実績・装備", "href": "board.html#students", "selector": "#rosterToggle"},
{"key": "roster-kenta79", "version": "day79-maintenance-1", "label": "健太 → 装着タリスマンの表示", "href": "board.html#student-10", "selector": "#rosterToggle"},
{key:"city66-68",version:"1-78",label:"新装備から黄金幻影へ・3話",href:"story/capital-city-days66-68.html",selector:"#guideToggle"},
{key:"city77",version:"1-77",label:"DAY67・王都の街路と根",href:"story/academy-day67.html",selector:"#guideToggle"},
{key:"equipment76",version:"1-76",label:"DAY66・戦利品の配分と新しい主力",href:"story/academy-day66.html",selector:"#rosterToggle"},
{key:"rematch64-65",version:"1-75",label:"再戦準備から勝利へ・2話",href:"story/capital-rematch-days64-65.html",selector:"#guideToggle"},
{key:"prepare-day64",version:"1-74",label:"DAY64・炎への備えと軍馬の世話",href:"story/academy-day64.html",selector:"#guideToggle"},
{key:"capital-days60-63",version:"1-73",label:"赤月から王都初戦へ・4話まとめ",href:"story/capital-approach-days60-63.html",selector:"#guideToggle"},
{key:"gate-day63",version:"1-73",label:"DAY63・王都への主力隊",href:"story/academy-day63.html",selector:"#guideToggle"},
{key:"gate-day62",version:"1-72",label:"DAY62・王都への主力隊",href:"story/academy-day62.html",selector:"#guideToggle"},
{key:"gate-day61",version:"1-71",label:"DAY61・王都への主力隊",href:"story/academy-day61.html",selector:"#guideToggle"},
{key:"redmoon60",version:"1-70",label:"DAY60赤月・教会の迎撃",href:"story/academy-day60.html",selector:"#guideToggle"},
{key:"capital-supply70",version:"1-70",label:"攻略：王都前の補給祝福",href:"guide.html#consequences/capital-supply",selector:"#guideToggle"},
{key:"scouting-summary59",version:"1-69",label:"円卓から王都門前へ・7日分の記録",href:"story/scouting-days53-59.html",selector:"#guideToggle"},
{key:"academy-day59",version:"1-69",label:"DAY59・偵察と二班の仕事",href:"story/academy-day59.html",selector:"#guideToggle"},
{key:"academy-day58",version:"1-68",label:"DAY58・偵察と二班の仕事",href:"story/academy-day58.html",selector:"#guideToggle"},
{key:"academy-day57",version:"1-67",label:"DAY57・偵察と二班の仕事",href:"story/academy-day57.html",selector:"#guideToggle"},
{key:"academy-day56",version:"1-66",label:"DAY56・王都外郭の地図",href:"story/academy-day56.html",selector:"#guideToggle"},
{key:"academy-day55",version:"1-65",label:"DAY55・武器強化と高原地図",href:"story/academy-day55.html",selector:"#guideToggle"},
{key:"academy-day54",version:"1-64",label:"DAY54・昇降機と高原の入口",href:"story/academy-day54.html",selector:"#guideToggle"},
{key:"academy-day53",version:"1-63",label:"DAY53・円卓で装備と育成",href:"story/academy-day53.html",selector:"#guideToggle"},
{key:"academy-day52",version:"1-62",label:"DAY52・レナラ戦と二つ目の大ルーン",href:"story/academy-day52.html",selector:"#guideToggle"},
{key:"academy-result62",version:"1-62",label:"攻略手帳・レナラ戦後の現在地",href:"guide.html#academy-plan",selector:"#guideToggle"},
 {key:"academy-five-days",version:"1-60",label:"DAY46–50：学院へ向かった五日間",href:"story/academy-days46-50.html",selector:"#routePlanLink"},
{key:'world-map57',version:"1-57",label:'全体地図・未解放祝福',href:'world-map.html',selector:'#routePlanLink'},
{key:'story-makoto57',version:"1-57",label:'誠：手を離しても（挿絵付き）',href:'side-stories.html#makoto-weight-of-one-stone',selector:'#rosterToggle'},
{key:'story-misaki57',version:"1-57",label:'美咲：曲がる角を、ひとつ（挿絵付き）',href:'side-stories.html#misaki-a-turn-she-remembers',selector:'#rosterToggle'},
{key:'reference-yota57',version:"1-57",label:'陽太：槍と革盾の新版資料',href:'board.html#student-11',selector:'#rosterToggle'},

 {key:"academy-plan57",version:"1-57",label:"学院の鍵・二つ目の大ルーン",href:"guide.html#consequences/academy-plan",selector:"#guideToggle"},
 {key:"five-day-summary",version:"1-56",label:"DAY42–46：五日分の物語と挿絵",href:"story/five-days-52-56.html",selector:"#routePlanLink"},
 {key:'boss-godrick51',version:'1-51',label:'城主撃破：現在地と祝福',href:'route-map.html#castle',selector:'#routePlanLink'},
 {key:'story-kaede',version:'1-51',label:'楓の掌編と挿絵：もう一人の手の場所',href:'side-stories.html#kaede-room-for-another-hand',selector:'#rosterToggle'},
{key:'reference-student-19',version:'day40-v2',label:'大地：最新版の装備三面図',href:'board.html#student-19',selector:'#rosterToggle'},
{key:'reference-student-01',version:'day40-v2',label:'直人：最新版の装備三面図',href:'board.html#student-01',selector:'#rosterToggle'},
{key:'roundtable-archive',version:'1-47',label:'円卓の補給：購入・祈祷・修理',href:'story/turn-1-47.html',selector:'#guideToggle'},
{key:'story-yota',version:'1-46',label:'陽太の掌編：痛いと言えた日',href:'side-stories.html#yota-saying-it-hurts',selector:'#rosterToggle'},
{key:'roster-growth',version:'1-56',label:'名鑑：探索隊と生活隊の成長',href:'board.html#students',selector:'#rosterToggle'},
{key:'guide-consequences',version:'1-49',label:'攻略考察：城内の現地記録',href:'guide.html#consequences',selector:'#guideToggle'},
{key:'supplies-water',version:'1-56',label:'資材：容器の買取と五日分の補給',href:'board.html#supplies-water',selector:'#suppliesToggle'},
{key:'route-map',version:'1-56',label:'作戦地図：塔制圧・左右割符・学院の門',href:'route-map.html#liurnia',selector:'#routePlanLink'},
{key:'guide-lore',version:'1-43',label:'攻略手帳：考察を読む',href:'guide.html#lore-review',selector:'#guideToggle'},
{key:'story-mio',version:'1-43',label:'名鑑：澪の掌編',href:'side-stories.html#mio-blank-in-the-record',selector:'#rosterToggle'},
{key:'story-ren',version:'1-43',label:'名鑑：蓮の掌編',href:'side-stories.html#ren-unused-route',selector:'#rosterToggle'},
{key:'art-yui',version:'1-44',label:'結衣の掌編・挿絵',href:'side-stories.html#yui-space-after-an-order',selector:'#rosterToggle'},
{key:'art-hana',version:'1-44',label:'花の掌編・挿絵',href:'side-stories.html#hana-counting-the-way-home',selector:'#rosterToggle'},
{key:'supplies-mount-care',version:'1-42',label:'資材：軍馬の世話',href:'board.html#supplies-horse',selector:'#suppliesToggle'}];
const memory=new Set();let list,button;const badges=[];
function read(e){if(memory.has(e.key))return true;try{return localStorage.getItem('isekai:new-content:'+e.key)===e.version}catch{return false}}
function mark(key){const e=entries.find(e=>e.key===key);if(!e)return;memory.add(key);try{localStorage.setItem('isekai:new-content:'+key,e.version)}catch{}render()}
function el(tag,text){const n=document.createElement(tag);if(text)n.textContent=text;return n}
function render(){if(!list)return;list.replaceChildren();for(const e of entries){const row=el('li'),a=el('a',e.label);a.href=e.href;a.addEventListener("click",()=>mark(e.key));row.append(a);if(!read(e)){const b=el('button','既読');b.type='button';b.setAttribute('aria-label',e.label+'を既読にする');b.onclick=()=>mark(e.key);row.append(b)}else row.append(el('small','既読'));list.append(row)}const count=entries.filter(e=>!read(e)).length;button.textContent='新着 '+count;for(const {node,selector}of badges)node.hidden=!entries.some(e=>e.selector===selector&&!read(e));window.dispatchEvent(new CustomEvent('isekai:new-content-change'))}
function markHref(href){for(const e of entries.filter(e=>e.href===href))mark(e.key)}
window.IsekaiNewContent={mark,markHref,isUnread:href=>entries.some(e=>e.href===href&&!read(e))};
function destination(){const path=location.pathname.split('/').pop(),hash=location.hash.slice(1);if((path==='board.html'||path==='index.html'||!path)&&hash==='students'){const b=document.getElementById('rosterToggle');if(b){b.click();mark('roster-growth')}}if(path==='turn-1-47.html')mark('roundtable-archive');if((path==='board.html'||path==='index.html'||!path)&&hash.startsWith('student-')){const id=hash;if(document.querySelector('.character-library[open] .character-detail'))mark('reference-'+id)}if(path==='side-stories.html'){const e=entries.find(e=>e.href==='side-stories.html#'+hash);if(e&&document.querySelector('#storyContent h2'))mark(e.key)}if(path==='guide.html'&&hash==='lore-review'){const n=document.getElementById('lore-review');if(n&&!n.closest('[hidden]')){n.classList.add('new-content-target');mark('guide-lore')}}if(path==='guide.html'&&hash==='consequences'){const n=document.getElementById('consequences');if(n&&!n.hidden){n.classList.add('new-content-target');mark('guide-consequences')}}if(path==='route-map.html'&&(hash==='overview'||hash==='castle'||hash==='liurnia'))mark('route-map');if((path==='board.html'||path==='index.html'||!path)&&(hash==='supplies-horse'||hash==='supplies-water')){const toggle=document.getElementById('suppliesToggle');if(!toggle)return;const open=document.querySelector('dialog.supplies-dialog[open]');if(!open)toggle.click();const section=[...document.querySelectorAll('.supplies-dialog h3')].find(n=>n.textContent===(hash==='supplies-water'?'水':'軍馬の世話'));if(section){section.id=hash;section.classList.add('new-content-target');section.scrollIntoView({block:'start'});mark(hash==='supplies-water'?'supplies-water':'supplies-mount-care')}}}
function mount(){const host=document.querySelector('body > header')||document.querySelector('header');if(!host)return;button=el('button');button.type='button';button.id='newContentToggle';button.setAttribute('aria-haspopup','dialog');const dialog=el('dialog');dialog.className='new-content-dialog';dialog.setAttribute('aria-labelledby','newContentTitle');const title=el('h2','新しく読めること');title.id='newContentTitle';const close=el('button','閉じる ×');close.type='button';close.onclick=()=>dialog.close();list=el('ul');dialog.append(close,title,list);document.body.append(dialog);host.append(button);button.onclick=()=>dialog.showModal();for(const selector of new Set(entries.map(e=>e.selector))){const target=document.querySelector(selector);if(!target)continue;const badge=el('span','NEW');badge.className='new-content-badge';target.append(badge);badges.push({node:badge,selector})}render();requestAnimationFrame(destination);window.addEventListener('hashchange',()=>requestAnimationFrame(destination));window.addEventListener('isekai:section-view',e=>mark(e.detail));window.addEventListener('storage',render);window.addEventListener('isekai:content-view',e=>markHref(e.detail))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
