(function(){'use strict';
const d=ROUTE_MAP_DATA,$=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg',key='isekai:route-map:view';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}let mode=['all','a','b','c','rescue'].includes(saved.mode)?saved.mode:'all',selected=d.nodes.some(n=>n.id===saved.selected)?saved.selected:d.initialSelection,fore=Boolean(saved.fore);
function el(t,text){const n=document.createElement(t);if(text!==undefined)n.textContent=text;return n}function svg(t,attrs={},text){const n=document.createElementNS(ns,t);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n}function save(){try{localStorage.setItem(key,JSON.stringify({mode,selected,fore}))}catch{}}
const labels={active:'解放済み・個人登録を確認',observed:'現地で確認',memory:'原作先読み・現地未確認',plan:'計画候補',reserve:'現地確認・未解放予備'};const colors={active:'#f0ce7d',observed:'#9dd8c0',memory:'#acbdce',plan:'#d8b875',reserve:'#e7c672'};
function select(id){if(!d.nodes.some(x=>x.id===id))return;selected=id;save();draw();detail();}
function detail(){const n=d.nodes.find(n=>n.id===selected),area=$('routeDetail');area.replaceChildren();if(d.completed)area.append(el('p',d.archiveNote));const tag=el('p',labels[n.status]);tag.className='eyebrow';area.append(tag,el('h2',fore&&n.foreTitle?n.foreTitle:n.title));for(const[label,text]of [['目的',n.purpose],['危険・注意',n.risks.join('／')],['まだ分からないこと',n.unknown],['次の判断',n.next]]){area.append(el('h3',label),el('p',text))}if(n.id==='medallion'&&fore)area.append(el('p','左：リムグレイブ東のハイト砦。右：ケイリッド竜塚のファロス砦。両片は実際に取得済み、DAY54デクタスを起動。個人の祝福登録は別。'));if(n.id==='castle'){const route=el('ol');route.className='castle-observed-route';route.setAttribute('aria-label','観測済みの城内経路');for(const point of ['崖脇道・ストームヴィル断崖（祝福未解放）','階段・暗室・錆鍵扉／梯子','外壁・城壁塔（祝福未解放）','戦鷹城壁・屋根道','礼拝堂：ロジェール会話','屋内・中庭','ネフェリと会話：助力了承','奥まった小部屋：解放済み・全33人個人登録','ゴドリック：撃破済み／撃破跡祝福は未解放'])route.append(el('li',point));area.append(el('h3','観測した通過順'),route,el('p','位置・距離を再現した図面ではありません。未踏部分の敵配置は含めていません。'));}for(const source of n.sources){const a=el('a',source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';const p=el('p');p.className='source';p.append(a);area.append(p)}area.scrollTop=0;}
function draw(){const canvas=$('routeCanvas');canvas.replaceChildren();const root=svg('svg',{viewBox:'0 0 1000 690',preserveAspectRatio:'xMidYMid meet',role:'group','aria-label':'作戦会議の概略図。地点はEnterで詳細表示'});canvas.append(root);root.append(svg('rect',{x:0,y:0,width:1000,height:690,rx:15,fill:'#161f21'}));const defs=svg('defs');const pat=svg('pattern',{id:'grid',width:36,height:36,patternUnits:'userSpaceOnUse'});pat.append(svg('path',{d:'M36 0H0V36',fill:'none',stroke:'#283435','stroke-width':.6}));defs.append(pat);root.append(defs,svg('rect',{width:1000,height:690,fill:'url(#grid)'}));root.append(svg('text',{x:660,y:30,fill:'#919e9b','font-size':12},'N ↑ 接続の概略／縮尺不正確'));
for(const e of d.edges){const a=d.nodes.find(n=>n.id===e.start),b=d.nodes.find(n=>n.id===e.end),active=mode==='all'||e.team.includes(mode);root.append(svg('path',{d:`M${a.x} ${a.y} Q${(a.x+b.x)/2+24} ${(a.y+b.y)/2} ${b.x} ${b.y}`,class:`route-edge ${e.status}${active?'':' muted'}`,fill:'none',stroke:colors[e.status], 'stroke-width':active?3:1.5,'stroke-dasharray':e.status==='observed'?'none':'7 8',opacity:active?.8:.15}));}
for(const n of d.nodes){const active=mode==='all'||n.team.includes(mode),g=svg('g',{class:`map-node ${n.status}${n.id===selected?' selected':''}${active?'':' muted'}`,transform:`translate(${n.x-96} ${n.y-37})`,tabindex:0,role:'button','aria-pressed':String(n.id===selected),'aria-label':n.title+'、'+labels[n.status]});g.append(svg('rect',{width:192,height:74,rx:10,fill:n.id===selected?'#293931':'#1d292b',stroke:colors[n.status],'stroke-width':n.id===selected?3:1.3,'stroke-dasharray':n.status==='reserve'?'5 3':'none'}));g.append(svg('text',{class:'node-title',x:12,y:25,fill:'#eee7d8','font-size':17,'font-weight':600},n.id==='medallion'&&fore?'割符：ハイト／ファロス':n.title));g.append(svg('text',{class:'node-subtitle',x:12,y:46,fill:colors[n.status],'font-size':12},n.subtitle));g.append(svg('text',{class:'node-status',x:12,y:63,fill:'#b2bcb7','font-size':10.5},labels[n.status]));g.addEventListener('click',()=>select(n.id));g.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();select(n.id);document.querySelector(`[aria-label="${n.title}、${labels[n.status]}"]`)?.focus();}});root.append(g);}
root.append(svg('text',{x:690,y:655,fill:'#b7c4c3','font-size':12},'実線：通過/確認の記録　点線：候補の接続'));
for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===mode));$('showForeknowledge').checked=fore;
}
$('campaignStatus').replaceChildren(...[`DAY${d.day} ${d.time}`,d.remaining,d.completed?'全33人帰還／地図は冒険中の記録':`全${d.people}人／${d.runes}ルーン`].map(x=>el('span',x)));
const box=$('teamSummary');box.replaceChildren();for(const t of d.teams){const card=el('article');card.append(el('h3',t.name+' · '+t.members.length+'人'),el('p',t.members.join('・')),el('p',t.task));box.append(card)}const intro=el('p',d.plan+' '+d.growth);intro.className='route-plan-note';document.querySelector('.map-column').prepend(intro);
for(const b of document.querySelectorAll('[data-view]')){if(b.dataset.view==='a')b.textContent='探索A隊';if(b.dataset.view==='b')b.textContent='探索B隊';b.addEventListener('click',()=>{mode=b.dataset.view;save();draw()})}
$('showForeknowledge').addEventListener('change',()=>{fore=$('showForeknowledge').checked;save();draw();detail()});$('resetView').addEventListener('click',()=>{mode='all';fore=false;selected=d.initialSelection;save();draw();detail()});
function hash(){const id=location.hash.slice(1);if(id==='overview'){mode='all';selected=d.initialSelection;save();draw();detail();return}if(d.nodes.some(n=>n.id===id))select(id)}draw();detail();hash();window.addEventListener('hashchange',hash);window.IsekaiLiveRefresh?.start({page:'routes',beforeReload:save});
})();
